name: Security Scan (CodeQL / Dependency / Secret Scanning)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 5 * * 1'

permissions:
  contents: read

jobs:
  analyze:
    name: Security Scan
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Fetch all history for all tags and branches for TruffleHog scanning

    - name: Run Secret Scanner (TruffleHog)
      uses: trufflesecurity/trufflehog@v3.82.6
      continue-on-error: true
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      continue-on-error: true # Ensure workflow doesn't fail if Code Scanning is not enabled in repo settings
      with:
        languages: 'javascript-typescript' # Setup typescript/javascript defaults

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3
      continue-on-error: true

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      continue-on-error: true
      with:
        category: "/language:javascript-typescript"
